spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_card_transactions?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mypassword
