spring:
  datasource:
    url: jdbc:mysql://localhost:3308/my_card_transactions?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: my-card-transactions-pwd
