spring:
  datasource:
    url: jdbc:mysql://localhost:3307/my_card_cards?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: my-card-cards-pwd
