spring:
  datasource:
    url: jdbc:mysql://localhost:3309/my_card_bill?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: my-card-bill-pwd
